parameters:
    database_driver:   pdo_sqlite
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     classroom
    database_user:     classroom
    database_password: ~
    database_path:     %kernel.root_dir%/data/classroom.db3

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
